{
 "title": "Farm Proxy Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "type", "label": "Hashrate type", "query": "standard,devfee" }
  ]
 },
 "panels": [
  {
   "title": "Instance information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "Version of Farm Proxy",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "FP_application_version_details", "legendFormat": "Version: {{version_full}}" }
     ]
    },
    {
     "title": "Braiins Product Stack",
     "type": "text",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "options": {
      "content": "<table width=\"100%\" style=\" border: none !important; table-layout: fixed; \" id=\"bps-table\">\n<tr>\n<td style=\"text-align: center; padding: 10px 0; width:50%;\"><a href=\"https://braiins.com/os-firmware?utm_source=Grafana&utm_medium=Dashboard_panel\" target=\"_blank\"><img src=\"/public/img/custom/braiins-os-logo-white.svg\" height=\"25px\" align=\"center\"></a></td>\n<td style=\"text-align: center; padding: 10px 0; width:50%;\"><a href=\"https://braiins.com/pool?utm_source=Grafana&utm_medium=Dashboard_panel\" target=\"_blank\"><img src=\"/public/img/custom/braiins-pool-logo-reverse-rgb.svg\" height=\"25px\"></a></td>\n</tr>\n<tr>\n<td style=\"text-align: center; padding: 10px 0;\"><a href=\"https://braiins.com/manager?utm_source=Grafana&utm_medium=Dashboard_panel\" target=\"_blank\" style=\"display:block\"><img src=\"/public/img/custom/braiins-manager-logo-white-rgb.svg\" height=\"25px\"></a></td>\n<td style=\"text-align: center; padding: 10px 0;\"><a href=\"https://braiins.com/toolbox?utm_source=Grafana&utm_medium=Dashboard_panel\" target=\"_blank\" style=\"display:block\"><img src=\"/public/img/custom/braiins-toolbox-logo-white-rgb.svg\" height=\"14px\"></a></td>\n</tr>\n<tr>\n<td style=\"text-align: center; padding: 10px 0;\"><a href=\"https://hashpower.braiins.com?utm_source=Grafana&utm_medium=Dashboard_panel\" target=\"_blank\" style=\"display:block\"><img src=\"/public/img/custom/braiins-hashpower-logo-white-rgb.svg\" height=\"18px\"></a></td>\n<td style=\"text-align: center; padding: 10px 0;\"><a href=\"https://braiins.com/farm-proxy?utm_source=Grafana&utm_medium=Dashboard_panel\" target=\"_blank\" style=\"display:block\"><img src=\"/public/img/custom/braiins-proxy-white-rgb.svg\" height=\"18px\"></a></td>\n</tr>\n</table>"
     },
     "targets": [
      {}
     ]
    },
    {
     "type": "stat",
     "description": "Days until certificate expires",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "FP_remaining_certificate_validity_days - (time() - FP_remaining_certificate_validity_check_ts) / 86400",
       "legendFormat": "certificate expires in:"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Most recent Farm Proxy start date",
     "gridPos": { "h": 1, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "FP_start_time_ms", "legendFormat": "started at:" }
     ]
    },
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 5 },
     "options": {
      "content": "Full documentation is available in the <a href=\"https://academy.braiins.com/en/farm-proxy/about\" target=\"_blank\">Braiins Academy</a> website"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Downstream hashrate",
   "type": "stat",
   "description": "Hashrate received from miners.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"down\", category=~\"$type\"}[5m]) * 4.294967296)",
     "legendFormat": "5min HR"
    },
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"down\", category=~\"$type\"}[1h]) * 4.294967296)",
     "legendFormat": "1hr HR"
    },
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"down\", category=~\"$type\"}[24h]) * 4.294967296)",
     "legendFormat": "24hr HR"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "stat",
   "description": "Hashrate sent to target pool(s).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"up\", category=~\"$type\"}[5m]) * 4.294967296)",
     "legendFormat": "5min HR"
    },
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"up\", category=~\"$type\"}[1h]) * 4.294967296)",
     "legendFormat": "1hr HR"
    },
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"up\",  category=~\"$type\"}[24h]) * 4.294967296)",
     "legendFormat": "24hr HR"
    }
   ]
  },
  {
   "title": "Downstream connections",
   "type": "stat",
   "description": "Count of currently connected miners by hashrate type",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "standard"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "devfee"
    }
   ]
  },
  {
   "title": "Upstream connections",
   "type": "stat",
   "description": "Count of connections to target pool(s) by hashrate type",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "standard"
    },
    {
     "expr": "sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "devfee"
    }
   ]
  },
  {
   "title": "Downstream shares",
   "type": "stat",
   "description": "Shares received from miners",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(FP_accepted_shares{direction=\"down\", category=~\"$type\"}[$__range]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(increase(FP_rejected_shares{direction=\"down\", category=~\"$type\"}[$__range]))",
     "legendFormat": "Invalid"
    },
    { "expression": "$B/($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Upstream shares",
   "type": "stat",
   "description": "Shares sent to target pool(s).",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(FP_accepted_shares{direction=\"up\", category=~\"$type\"}[$__range]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(increase(FP_rejected_shares{direction=\"up\",category=~\"$type\"}[$__range]))",
     "legendFormat": "Invalid"
    },
    { "expression": "$B/($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Connected miners",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "Standard"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})",
     "legendFormat": "Devfee"
    }
   ]
  },
  {
   "title": "Downstream hashrate",
   "type": "timeseries",
   "description": "Hashrate received from miners",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"down\", category=~\"$type\"}[5m]) * 4.294967296) by (category)",
     "legendFormat": "{{category}} hashrate (accepted)"
    },
    {
     "expr": "sum(rate(FP_rejected_shares{direction=\"down\", category=~\"$type\"}[1m]) * 4.294967296) by (category)",
     "legendFormat": "{{category}} hashrate (invalid)"
    }
   ]
  },
  {
   "title": "Aggregation",
   "type": "stat",
   "description": "Theoretical aggregation based on ratio of upstream and downstream connections. Theoretical means the real aggregation can be lower due to network events (e.g. reconnections or job resets).",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Standard HR"
    },
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Devfee HR"
    }
   ]
  },
  {
   "title": "Upstream hashrate",
   "type": "timeseries",
   "description": "Hashrate sent to target pool(s)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_accepted_shares{direction=\"up\", category=~\"$type\"}[5m]) * 4.294967296) by (category)",
     "legendFormat": "{{category}} hashrate (accepted)"
    },
    {
     "expr": "sum(rate(FP_rejected_shares{direction=\"up\", category=~\"$type\"}[1m]) * 4.294967296) by (category)",
     "legendFormat": "{{category}} hashrate (invalid)"
    }
   ]
  },
  {
   "title": "Aggregation history",
   "type": "timeseries",
   "description": "History of theoretical aggregation",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Standard HR"
    },
    {
     "expr": "clamp_min(100 - (sum(FP_connections_by_target{goal=\"#!!ii-DevFee\"}) / sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})) * 100, 0)",
     "legendFormat": "Devfee HR"
    }
   ]
  },
  {
   "title": "Devfee Licenses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "timeseries",
     "description": "Overview of Braiins OS licenses on devices connected to the Farm Proxy.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "FP_license_prov_license_counts_by_state>0",
       "legendFormat": "{{contract_name}} ({{license_state}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Hashrate split",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Split among targets",
     "type": "piechart",
     "description": "Split of standard hashrate among targets (IP addresses behind pool URL).",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(FP_accepted_shares{direction=\"up\", category=\"standard\"}[5m])) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    }
   ]
  }
 ]
}