{
 "title": "Debug Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "reason",
    "query": {
     "query": "label_values(FP_rejected_shares, reason)"
    }
   },
   { "name": "direction", "query": "up,down" },
   { "name": "type", "query": "standard,devfee" },
   {
    "name": "target",
    "query": {
     "query": "label_values(FP_connections_by_target, target)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Version of Farm Proxy",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "FP_application_version_details", "legendFormat": "Version: {{version_full}}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}} (virtual)" },
    {
     "expr": "sum(process_resident_memory_bytes) by (job)",
     "legendFormat": "{{job}} (resident)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FP_start_time_ms",
     "legendFormat": "Router start time ({{instance}}):"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "FP_remaining_certificate_validity_days - (time() - FP_remaining_certificate_validity_check_ts) / 86400",
     "legendFormat": "Certificate expires in"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{target=~\"$target\"}) + sum(FP_subscription_size_to_target_total{target=~\"$target\"})",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "downstream standard open connection {{goal}}"
    },
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "downstream devfee open connection"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "upstream standard open connection"
    },
    {
     "expr": "sum(FP_connections_by_target{goal=\"#!!ii-DevFee\",target=~\"$target\"})",
     "legendFormat": "upstream devfee open connection"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "timeseries",
   "description": "Last 30s hashrate based on selected filter.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "GHs" } },
   "targets": [
    {
     "expr": "sum(rate(FP_accepted_shares{direction=~\"$direction\",category=~\"$type\"}[30s]) * 4.294967296) by (target, direction, category)",
     "legendFormat": "{{target}} accepted {{direction}} {{category}} hashrate"
    }
   ]
  },
  {
   "title": "Submission Rate",
   "type": "timeseries",
   "description": "Last 30s submission rate based on selected filters.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(FP_accepted_submits{direction=~\"$direction\",category=~\"$type\"}[30s])) by (target, direction, category)",
     "legendFormat": "{{target}} accepted {{direction}} {{category}} submits"
    }
   ]
  },
  {
   "title": "Hashrate Split",
   "type": "timeseries",
   "description": "Split of hashrate in case multiple goals are defined.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(FP_optimizer_hash_rate_split{goal!=\"#!!ii-DevFee\", type=\"allocated_hr\"}) by (goal)",
     "legendFormat": "{{goal}}"
    }
   ]
  },
  {
   "title": "Connection metrics - Standard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream connections",
   "type": "timeseries",
   "description": "Number of connected miners.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"})",
     "legendFormat": "Downstream connections"
    }
   ]
  },
  {
   "title": "Downstream connections close side",
   "type": "timeseries",
   "description": "Overview of who closed the connection in case it was closed (internal = Farm Proxy, external = miner).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(FP_dn_connection_close_side{type=\"standard\"}[30s])*15",
     "legendFormat": "{{direction}} ({{side}})"
    }
   ]
  },
  {
   "title": "Connection to upstream",
   "type": "timeseries",
   "description": "Number of connections greater than 0 to upstream.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(FP_connections_by_target{goal!=\"#!!ii-DevFee\"}) by (target, goal) > 0",
     "legendFormat": "{{goal}} {{target}}"
    }
   ]
  },
  {
   "title": "Subscription by target",
   "type": "timeseries",
   "description": "How many miners subscribed to which target.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(FP_subscription_size_to_target_total{goal!=\"#!!ii-DevFee\"}) by (goal, target) > 0",
     "legendFormat": "{{goal}} - {{target}}"
    }
   ]
  },
  {
   "title": "Score by target",
   "type": "timeseries",
   "description": "Score is calculated from latency, rejection rate and error rate. If current target's score is too high, Farm proxy switches to target with lower score.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(FP_score_by_target{target!~\".*Devfee.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Rejection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(FP_rejection_rate{target!~\".*Devfee.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(FP_mean_latency_s{target!~\".*Devfee.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Error rate is rate of errors in communication to upstream (i.e. timeouts).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(FP_error_rate{target!~\".*Devfee.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Reason for Target Down",
   "type": "timeseries",
   "description": "Target can be marked as \"down\" from various reasons. Target in \"down\" status is not available for receiving hashrate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(increase(FP_target_down_reason_total{target!~\".*Devfee.*\"}[30s])) by (reason, target)",
     "legendFormat": "{{target}} {{reason}}"
    }
   ]
  },
  {
   "title": "Target Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum(FP_target_status{target!~\".*Devfee.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Target Status History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum(FP_target_status{target!~\".*Devfee.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Connection metrics - Devfee",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Downstream connections",
     "type": "timeseries",
     "description": "Number of connected devfee miners.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\"})",
       "legendFormat": "Downstream connections"
      }
     ]
    },
    {
     "title": "Connection to upstream",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(FP_connections_by_target{target=~\"$target\", goal=\"#!!ii-DevFee\"}) by (target, goal) > 0",
       "legendFormat": "{{goal}} {{target}}"
      }
     ]
    },
    {
     "title": "Subscription by target - devfee",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(FP_subscription_size_to_target_total{goal=\"#!!ii-DevFee\",target=~\"$target\"}) by (goal, target) > 0",
       "legendFormat": "{{goal}} - {{target}}"
      }
     ]
    },
    {
     "title": "Score by target",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(FP_score_by_target{target=~\".*Devfee.*\"}) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Rejection rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(FP_rejection_rate{target=~\".*Devfee.*\"}) by (target) > 0",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Mean latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(FP_mean_latency_s{target=~\".*Devfee.*\"}) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(FP_error_rate{target=~\".*Devfee.*\"}) by (target) > 0",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Reason for Target Down",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(FP_target_down_reason_total{target=~\".*Devfee.*\"}[30s])) by (reason, target)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Target Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "sum(FP_target_status{target=~\".*Devfee.*\"}) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Target Status",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "sum(FP_target_status{target=~\".*Devfee.*\"}) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Farm Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "#New Certificates",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(FP_cert_refresh_total)", "legendFormat": "#New Certificates" }
     ]
    },
    {
     "title": "#Active connection",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "FP_farm_management_number_active_connection_total",
       "legendFormat": "#Active connection"
      }
     ]
    },
    {
     "title": "Farm management problems",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sum(rate(FP_farm_management_submit_data_error_total[60m])) by (reason)",
       "legendFormat": "#data sent failed {{reason}}"
      },
      {
       "expr": "sum(rate(FP_farm_management_data_failed_total[60m])) by (reason)",
       "legendFormat": "#data sent failed {{reason}}"
      },
      {
       "expr": "sum(rate(FP_cert_refresh_failed_total[60m])) by (reason)",
       "legendFormat": "#certificate refresh failed {{reason}}"
      }
     ]
    },
    {
     "title": "#received messages/data per hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "sum(rate(FP_farm_management_telemetry_payload_recv_total[60m]))",
       "legendFormat": "#received messages"
      },
      {
       "expr": "sum(rate(FP_farm_management_data_recv_total[60m]))",
       "legendFormat": "#received data"
      },
      {
       "expr": "sum(rate(FP_farm_management_batch_ticks_total[60m]))",
       "legendFormat": "#batch ticks"
      }
     ]
    },
    {
     "title": "#Device registration",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "FP_farm_management_accepted_device_registration_total",
       "legendFormat": "#device accepted registration"
      },
      {
       "expr": "FP_farm_management_rejected_device_registration_total",
       "legendFormat": "#device rejected registration"
      }
     ]
    }
   ]
  }
 ]
}